version: "3.8"
services:
  todo-service-ui:
    image: hnjaman/todo-service-ui:latest
    container_name: todo-service-ui
    depends_on:
      - todo-service
    ports:
      - 80:80
  todo-service:
    image: hnjaman/todo-service:latest
    container_name: todo-service
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      -  ./db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: 1111


