apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: LoadBalancer  # Or NodePort based on your requirement
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: todo-backend